# Generated by Django 3.1.14 on 2022-04-25 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_remove_articles_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/%y'),
            preserve_default=False,
        ),
    ]
