# Generated by Django 3.1.14 on 2022-04-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutMe', models.TextField(max_length=8050)),
                ('aboutBlog', models.TextField(max_length=8050)),
                ('mySkills', models.TextField(max_length=8050)),
                ('myProjects', models.TextField(max_length=8050)),
                ('img', models.ImageField(upload_to='images/%y')),
            ],
        ),
    ]
