# Generated by Django 3.1.14 on 2022-04-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='img',
        ),
    ]
