# Generated by Django 3.1.14 on 2022-04-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_articles_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(max_length=8050),
        ),
        migrations.AlterField(
            model_name='articles',
            name='subtitle',
            field=models.TextField(max_length=855),
        ),
    ]
