# Generated by Django 3.1.14 on 2022-05-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0012_auto_20220526_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='emailAddress',
            field=models.EmailField(max_length=255),
        ),
    ]
